### ISSUE TITLE
some stream is ended, but still showing in live items

### ISSUE THREAD

**Issue by sinkaroid** [noaione/vtbili-schedule#1]
hello
i implemented this api into my discord bot since nov 2020 iirc.
seems v1 deprecated so i using your v2 graphql instead

**but sometimes items are outdated, its said still live but actually ended 11 hours ago.**
thankyou so much for this beautiful api, I will close this issue immediately when I get any answer

**Comment by noaione** [comment]
The website is currently "offline" since I was migrating to a new schema and haven't completed yet the API migration to use the new schema, it's possibly done in about 2 hours before the API will be live again

Currently testing to make sure nothing is broken

**Comment by noaione** [comment]
The schema I mention here is the database schema btw, there will be no changes to the GraphQL schema

**Comment by noaione** [comment]
Website should be back and working properly
